export default {
    SIGN_UP: '/register',
    HOME: '/',
    SING_IN: '/login',
    ABOUT: '/about',
    SHOP: '/shop',
    SHOPPING_CART: '/shopping-cart',
    PROFILE: '/profile/',
    ADMIN: '/admin',
    SHOP: '/shop',
    CASES: '/shop/cases',
    PROTECTORS: '/shop/protectors',
    CABLES: '/shop/cables',
    DETAILS: '/shop/details/',
};
